# What we want !
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: mongodb-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi


---
# How do we want !

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: mongodb-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/krishna/db/mongodb"
    type: DirectoryOrCreate

